2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_setup.py:_flush():76] Configure stats pid to 93528
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_setup.py:_flush():76] Loading settings from /Users/balthazarmartin/.config/wandb/settings
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_setup.py:_flush():76] Loading settings from /Users/balthazarmartin/Documents/ICL/Individual Project/programs/wandb/settings
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/Users/balthazarmartin/Documents/ICL/Individual Project/programs/main.py', 'program': '/Users/balthazarmartin/Documents/ICL/Individual Project/programs/main.py'}
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_init.py:_log_setup():526] Logging user logs to /Users/balthazarmartin/Documents/ICL/Individual Project/programs/wandb/run-20250126_122025-mjcrxgkb/logs/debug.log
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/balthazarmartin/Documents/ICL/Individual Project/programs/wandb/run-20250126_122025-mjcrxgkb/logs/debug-internal.log
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_init.py:init():566] calling init triggers
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_init.py:init():616] starting backend
2025-01-26 12:20:25,763 INFO    MainThread:93528 [wandb_init.py:init():620] setting up manager
2025-01-26 12:20:25,767 INFO    MainThread:93528 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-01-26 12:20:25,770 INFO    MainThread:93528 [wandb_init.py:init():628] backend started and connected
2025-01-26 12:20:25,779 INFO    MainThread:93528 [wandb_init.py:init():720] updated telemetry
2025-01-26 12:20:25,800 INFO    MainThread:93528 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2025-01-26 12:20:26,125 ERROR   MainThread:93528 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2025-01-26 12:20:26,249 ERROR   MainThread:93528 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/balthazarmartin/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/balthazarmartin/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2025-01-26 12:20:27,266 WARNING MsgRouterThr:93528 [router.py:message_loop():77] message_loop has been closed
